version: '3.8'

services:
  springboot-app:
    image: openjdk:17-jdk-slim
    depends_on:
      postgres:
        condition: service_healthy
    container_name: springboot-app
    ports:
      - "8080:8080"
    volumes:
      - ./target/h2h-combat-back-0.0.1-SNAPSHOT.jar:/app/h2h-combat-back.jar
    command: [ "java", "-jar", "/app/h2h-combat-back.jar" ]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/rps_jcazalil
      - SPRING_DATASOURCE_USERNAME=abc
      - SPRING_DATASOURCE_PASSWORD=abc
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always
      - MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED=true
    networks:
      - monitoring
  postgres:
    image: postgres:latest
    container_name: postgres_db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "abc", "-d", "rps_jcazalil" ]
      interval: 10s
      retries: 5
    environment:
      POSTGRES_DB: rps_jcazalil
      POSTGRES_USER: abc
      POSTGRES_PASSWORD: abc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monitoring

  elasticsearch:
    image: elasticsearch:8.4.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

volumes:
  postgres_data:
  esdata:
  grafana-data:
  prometheus-data:

networks:
  elastic_network:
    driver: bridge
  monitoring:
    driver: bridge